package config

import "flag"

// RegisterFlags binds all CLI flags to opts fields.
func RegisterFlags(fs *flag.FlagSet, opts *CLIOptions) {
	fs.StringVar(&opts.PaneID, "pane", "", "Target tmux pane ID (required unless --demo)")
	fs.StringVar(&opts.Mode, "mode", DefaultMode, "Line number mode (absolute, relative, hybrid)")
	fs.IntVar(&opts.ScrollbackLines, "scrollback-lines", DefaultScrollbackLines, "Lines of scrollback to capture (100-200000)")
	fs.StringVar(&opts.Theme, "theme", DefaultTheme, "Theme preset (default, dracula, gruvbox, nord, solarized)")
	fs.BoolVar(&opts.Demo, "demo", false, "Run in demo mode (no tmux pane required)")
	fs.StringVar(&opts.CursorFG, "cursor-fg", "", "Cursor foreground color (#RRGGBB)")
	fs.StringVar(&opts.CursorBG, "cursor-bg", "", "Cursor background color (#RRGGBB)")
	fs.StringVar(&opts.SelectionFG, "selection-fg", "", "Selection foreground color (#RRGGBB)")
	fs.StringVar(&opts.SelectionBG, "selection-bg", "", "Selection background color (#RRGGBB)")
	fs.StringVar(&opts.GutterFG, "gutter-fg", "", "Gutter foreground color (#RRGGBB)")
	fs.StringVar(&opts.GutterBG, "gutter-bg", "", "Gutter background color (#RRGGBB)")
	fs.StringVar(&opts.GutterSeparatorFG, "gutter-separator-fg", "", "Gutter separator foreground color (#RRGGBB)")
	fs.StringVar(&opts.GutterSeparatorBG, "gutter-separator-bg", "", "Gutter separator background color (#RRGGBB)")
	fs.StringVar(&opts.GutterSeparatorChar, "gutter-separator-char", "", "Gutter separator character (single printable rune)")
	fs.StringVar(&opts.LineNumAbsoluteFG, "linenum-absolute-fg", "", "Absolute line number foreground color (#RRGGBB)")
	fs.StringVar(&opts.LineNumRelativeFG, "linenum-relative-fg", "", "Relative line number foreground color (#RRGGBB)")
	fs.StringVar(&opts.LineNumCursorFG, "linenum-cursor-fg", "", "Cursor line number foreground color (#RRGGBB)")
	fs.StringVar(&opts.LineNumCursorBold, "linenum-cursor-bold", "", "Cursor line bold (on, off)")
	fs.StringVar(&opts.StatusFG, "status-fg", "", "Status indicator foreground color (#RRGGBB)")
	fs.StringVar(&opts.StatusBG, "status-bg", "", "Status indicator background color (#RRGGBB)")

	// TextStyle override flags
	fs.StringVar(&opts.LineNumAbsoluteBold, "linenum-absolute-bold", "", "Absolute line number bold (on, off)")
	fs.StringVar(&opts.LineNumAbsoluteDim, "linenum-absolute-dim", "", "Absolute line number dim (on, off)")
	fs.StringVar(&opts.LineNumAbsoluteItalic, "linenum-absolute-italic", "", "Absolute line number italic (on, off)")
	fs.StringVar(&opts.LineNumRelativeBold, "linenum-relative-bold", "", "Relative line number bold (on, off)")
	fs.StringVar(&opts.LineNumRelativeDim, "linenum-relative-dim", "", "Relative line number dim (on, off)")
	fs.StringVar(&opts.LineNumRelativeItalic, "linenum-relative-italic", "", "Relative line number italic (on, off)")
	fs.StringVar(&opts.LineNumCursorDim, "linenum-cursor-dim", "", "Cursor line number dim (on, off)")
	fs.StringVar(&opts.LineNumCursorItalic, "linenum-cursor-italic", "", "Cursor line number italic (on, off)")
	fs.StringVar(&opts.StatusBold, "status-bold", "", "Status bar bold (on, off)")
	fs.StringVar(&opts.StatusDim, "status-dim", "", "Status bar dim (on, off)")
	fs.StringVar(&opts.CursorDim, "cursor-dim", "", "Cursor dim (on, off)")
	fs.StringVar(&opts.CursorItalic, "cursor-italic", "", "Cursor italic (on, off)")
	fs.StringVar(&opts.SelectionDim, "selection-dim", "", "Selection dim (on, off)")
	fs.StringVar(&opts.SelectionItalic, "selection-italic", "", "Selection italic (on, off)")

	fs.StringVar(&opts.ToggleModeKey, "toggle-mode-key", DefaultToggleModeKey, "Key to toggle line number mode (single ASCII char)")
	fs.StringVar(&opts.WrapKey, "wrap-key", DefaultWrapKey, "Key to toggle wrap mode after g prefix (single ASCII char)")
	fs.StringVar(&opts.CopyTarget, "copy-target", DefaultCopyTarget, "Copy destination (both, tmux, clipboard)")
	fs.StringVar(&opts.ExitOnYank, "exit-on-yank", DefaultExitOnYank, "Exit TUI after yanking (on, off)")
	fs.StringVar(&opts.StartPosition, "start-position", DefaultStartPosition, "Initial cursor position (top, middle, bottom)")
	fs.StringVar(&opts.WrapMode, "wrap-mode", DefaultWrapMode, "Long line wrapping (on, off)")
	fs.StringVar(&opts.StatusBar, "status-bar", DefaultStatusBar, "Powerline status bar (on, off)")
	fs.StringVar(&opts.Bindings, "bindings", "", "Key binding overrides (comma-separated key=action, !key to unbind)")
	fs.StringVar(&opts.NormalBindings, "nbindings", "", "Normal-mode binding overrides (comma-separated key=action, !key to unbind)")
	fs.StringVar(&opts.VisualBindings, "vbindings", "", "Visual-mode binding overrides (comma-separated key=action, !key to unbind)")

	// Flash navigation
	fs.StringVar(&opts.Flash, "flash", "on", "Flash navigation mode (on, off)")
	fs.StringVar(&opts.FlashMinChars, "flash-min-chars", "1", "Minimum chars before flash labels appear")
	fs.StringVar(&opts.FlashFT, "flash-ft", "off", "Flash labels for f/t motions (on, off)")
	fs.StringVar(&opts.FlashLabelFG, "flash-label-fg", "", "Flash label foreground color (#RRGGBB)")
	fs.StringVar(&opts.FlashLabelBG, "flash-label-bg", "", "Flash label background color (#RRGGBB)")
	fs.StringVar(&opts.FlashMatchFG, "flash-match-fg", "", "Flash match foreground color (#RRGGBB)")
	fs.StringVar(&opts.FlashMatchBG, "flash-match-bg", "", "Flash match background color (#RRGGBB)")
	fs.StringVar(&opts.FlashBackdrop, "flash-backdrop", "", "Flash backdrop foreground color (#RRGGBB)")
	fs.StringVar(&opts.FlashJumpPos, "flash-jump-pos", "match_end", "Flash label jump position (match_start, match_end, word_start, word_end)")
	fs.StringVar(&opts.FlashAltJumpPos, "flash-alt-jump-pos", "match_start", "Flash Shift+label jump position (match_start, match_end, word_start, word_end, off)")
}
